// Code generated by protoc-gen-go.
// source: cs_msg_id.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	cs_msg_id.proto
	cs_common.proto
	cs_login_sys.proto
	cs_sundry_sys.proto
	ss_base.proto
	ss_logic.proto
	db.proto
	ts_common.proto
	ts_server.proto
	ts_client.proto

It has these top-level messages:
	C2SClientSessionPing
	S2CClientSessionPong
	CsAccountRegisterReq
	ScAccountRegisterAck
	CsAccountLoginReq
	ScAccountLoginAck
	CsGameLoginReq
	PlayerBaseInfo
	ScGameLoginAck
	CsCreatePlayerReq
	ScCreatePlayerAck
	CsSelectPlayerReq
	ScSelectPlayerAck
	CsReconnectGameReq
	ScReconnectGameAck
	CsExitGameReq
	CsTestPressureReq
	ScTestPressureAck
	CsGmReq
	ScServerTimeNtf
	ScErrorcodeNtf
	ScTipNtf
	S2SServerSessionVeriryReq
	S2SServerSessionVeriryAck
	S2SServerSessionPing
	S2SServerSessionPong
	S2SClientSessionPing
	S2SClientSessionPong
	SdConnAttr
	ServiceDiscovery
	ServiceDiscoveryReq
	ServiceDiscoveryAck
	GlGatewayInfoNtf
	GlVerifyTokenReq
	LgVerifyTokenAck
	SsPlayerBaseInfo
	HcSelectPlayerListReq
	ChSelectPlayerListAck
	HcCreatePlayerReq
	ChCreatePlayerAck
	HdCreatePlayerReq
	DhCreatePlayerAck
	GhSelectHallReq
	HgSelectHallAck
	S2S2CHgcTranferMsg
	S2SHcTranferMsg
	S2SGhTranferMsg
	S2SGhExitGameReq
	S2SGhKickPlayerReq
	S2SLghKickPlayerReq
	S2SHglKickPlayerAck
	S2SGhReconnectGameReq
	DbBinary
	RankItem
	Ts2TsGatewayInfoNtf
	Ts2TsGrTranferMsg
	Ts2TsRgTranferMsg
	C2TsSelectTsgateReq
	Ts2CSelectTsgateAck
	C2TsTsgateVerifyReq
	Ts2CTsgateVerifyAck
	C2TsCgTranferMsg
	Ts2CGcTranferMsg
	C2TsUpdateRankReq
	Ts2CUpdateRankAck
	C2TsQueryRankReq
	Ts2CQueryRankAck
	C2TsClearAllReq
	Ts2CClearAllAck
	C2TsClearPlayerReq
	Ts2CClearPlayerAck
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type EClient2GameMsgId int32

const (
	EClient2GameMsgId_cs_engine_min_msg_id       EClient2GameMsgId = 0
	EClient2GameMsgId_c2s_client_session_ping_id EClient2GameMsgId = 1
	EClient2GameMsgId_s2c_client_session_pong_id EClient2GameMsgId = 2
	EClient2GameMsgId_sc_engine_min_msg_id       EClient2GameMsgId = 299
	EClient2GameMsgId_cs_logic_min_msg_id        EClient2GameMsgId = 300
	EClient2GameMsgId_cs_account_register_req_id EClient2GameMsgId = 301
	EClient2GameMsgId_sc_account_register_ack_id EClient2GameMsgId = 302
	EClient2GameMsgId_cs_account_login_req_id    EClient2GameMsgId = 303
	EClient2GameMsgId_sc_account_login_ack_id    EClient2GameMsgId = 304
	EClient2GameMsgId_cs_game_login_req_id       EClient2GameMsgId = 305
	EClient2GameMsgId_sc_game_login_ack_id       EClient2GameMsgId = 306
	EClient2GameMsgId_cs_create_player_req_id    EClient2GameMsgId = 307
	EClient2GameMsgId_sc_create_player_ack_id    EClient2GameMsgId = 308
	EClient2GameMsgId_cs_select_player_req_id    EClient2GameMsgId = 309
	EClient2GameMsgId_sc_select_player_ack_id    EClient2GameMsgId = 310
	EClient2GameMsgId_cs_exit_game_req_id        EClient2GameMsgId = 311
	EClient2GameMsgId_cs_reconnect_game_req_id   EClient2GameMsgId = 312
	EClient2GameMsgId_sc_reconnect_game_ack_id   EClient2GameMsgId = 313
	EClient2GameMsgId_sc_server_time_ntf_id      EClient2GameMsgId = 314
	EClient2GameMsgId_cs_gm_req_id               EClient2GameMsgId = 315
	EClient2GameMsgId_sc_tip_ntf_id              EClient2GameMsgId = 316
	EClient2GameMsgId_sc_errorcode_ntf_id        EClient2GameMsgId = 317
	EClient2GameMsgId_sc_logic_max_msg_id        EClient2GameMsgId = 65535
)

var EClient2GameMsgId_name = map[int32]string{
	0:     "cs_engine_min_msg_id",
	1:     "c2s_client_session_ping_id",
	2:     "s2c_client_session_pong_id",
	299:   "sc_engine_min_msg_id",
	300:   "cs_logic_min_msg_id",
	301:   "cs_account_register_req_id",
	302:   "sc_account_register_ack_id",
	303:   "cs_account_login_req_id",
	304:   "sc_account_login_ack_id",
	305:   "cs_game_login_req_id",
	306:   "sc_game_login_ack_id",
	307:   "cs_create_player_req_id",
	308:   "sc_create_player_ack_id",
	309:   "cs_select_player_req_id",
	310:   "sc_select_player_ack_id",
	311:   "cs_exit_game_req_id",
	312:   "cs_reconnect_game_req_id",
	313:   "sc_reconnect_game_ack_id",
	314:   "sc_server_time_ntf_id",
	315:   "cs_gm_req_id",
	316:   "sc_tip_ntf_id",
	317:   "sc_errorcode_ntf_id",
	65535: "sc_logic_max_msg_id",
}
var EClient2GameMsgId_value = map[string]int32{
	"cs_engine_min_msg_id":       0,
	"c2s_client_session_ping_id": 1,
	"s2c_client_session_pong_id": 2,
	"sc_engine_min_msg_id":       299,
	"cs_logic_min_msg_id":        300,
	"cs_account_register_req_id": 301,
	"sc_account_register_ack_id": 302,
	"cs_account_login_req_id":    303,
	"sc_account_login_ack_id":    304,
	"cs_game_login_req_id":       305,
	"sc_game_login_ack_id":       306,
	"cs_create_player_req_id":    307,
	"sc_create_player_ack_id":    308,
	"cs_select_player_req_id":    309,
	"sc_select_player_ack_id":    310,
	"cs_exit_game_req_id":        311,
	"cs_reconnect_game_req_id":   312,
	"sc_reconnect_game_ack_id":   313,
	"sc_server_time_ntf_id":      314,
	"cs_gm_req_id":               315,
	"sc_tip_ntf_id":              316,
	"sc_errorcode_ntf_id":        317,
	"sc_logic_max_msg_id":        65535,
}

func (x EClient2GameMsgId) String() string {
	return proto.EnumName(EClient2GameMsgId_name, int32(x))
}
func (EClient2GameMsgId) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("pb.EClient2GameMsgId", EClient2GameMsgId_name, EClient2GameMsgId_value)
}

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0x49, 0x4e, 0x03, 0x31,
	0x10, 0x45, 0xc1, 0x08, 0x16, 0x16, 0x08, 0x62, 0x82, 0x08, 0x11, 0xc3, 0x9e, 0x05, 0x8b, 0x70,
	0x04, 0x16, 0x88, 0x05, 0x67, 0xb0, 0x3a, 0x4e, 0xd1, 0xb2, 0xe8, 0xb6, 0x1b, 0xdb, 0xa0, 0x70,
	0x19, 0x2e, 0xc0, 0x3c, 0xcf, 0x67, 0x0b, 0x65, 0xc7, 0x86, 0x4e, 0xc2, 0x2e, 0xd2, 0xab, 0xf7,
	0x7f, 0xa5, 0xdc, 0x74, 0x51, 0x58, 0x5e, 0xda, 0x9c, 0xcb, 0xde, 0x4e, 0x65, 0xb4, 0xd3, 0x8c,
	0x54, 0xdd, 0xed, 0x8b, 0x59, 0xda, 0x80, 0xbd, 0x42, 0x82, 0x72, 0x9d, 0xfd, 0xac, 0x84, 0x43,
	0x9b, 0x1f, 0xf4, 0x58, 0x8b, 0x36, 0x71, 0x18, 0x54, 0x2e, 0x15, 0xf0, 0x52, 0xaa, 0xe8, 0x2d,
	0x4d, 0xb1, 0x4d, 0xda, 0x16, 0x1d, 0xcb, 0x45, 0x30, 0xb8, 0x05, 0x6b, 0xa5, 0x56, 0xbc, 0x92,
	0x2a, 0xf0, 0x69, 0xcf, 0x6d, 0x47, 0x4c, 0x70, 0x3d, 0xe4, 0x84, 0xad, 0xd1, 0xa6, 0x15, 0xff,
	0x24, 0x5f, 0x12, 0x2c, 0x5d, 0xc6, 0xd2, 0x42, 0xe7, 0x52, 0xd4, 0xc9, 0x15, 0x61, 0x5b, 0x58,
	0x6a, 0x79, 0x26, 0x84, 0x3e, 0xc5, 0x50, 0x03, 0xb9, 0xb4, 0x0e, 0x0c, 0xfe, 0x38, 0xf1, 0x03,
	0xd7, 0x61, 0x00, 0x53, 0x27, 0x06, 0x32, 0x71, 0xec, 0x07, 0x6e, 0x08, 0x5b, 0xa7, 0xab, 0xb5,
	0x04, 0xdf, 0xa1, 0x92, 0x7e, 0x1b, 0x68, 0x4d, 0x1f, 0xd2, 0xe8, 0xde, 0x85, 0x95, 0xd1, 0xcd,
	0xf1, 0x38, 0xa3, 0xe2, 0x7d, 0xfa, 0x37, 0x35, 0x14, 0xad, 0x87, 0xd4, 0x28, 0x0c, 0x64, 0x0e,
	0x78, 0x55, 0x64, 0xe7, 0x7f, 0x0b, 0x3f, 0xa6, 0xc6, 0x51, 0x1a, 0xdd, 0xa7, 0xe4, 0x5a, 0x28,
	0x40, 0xb8, 0x31, 0xf7, 0x39, 0xb9, 0xa3, 0x34, 0xba, 0x2f, 0xe9, 0x8a, 0xd0, 0x97, 0x6e, 0xb8,
	0x57, 0xf4, 0x5e, 0x09, 0xdb, 0xa0, 0x2d, 0x24, 0x06, 0x84, 0x56, 0xca, 0xab, 0x75, 0xfc, 0x16,
	0x30, 0xc6, 0x8e, 0xe1, 0x98, 0xfb, 0x4e, 0x58, 0x9b, 0xae, 0x84, 0x56, 0x73, 0x86, 0x75, 0x4e,
	0x22, 0x53, 0xee, 0xc8, 0xb3, 0x0f, 0xc2, 0x1a, 0x74, 0xde, 0x5f, 0xa8, 0x4c, 0x69, 0x9f, 0x84,
	0x31, 0xba, 0x80, 0xe3, 0x4e, 0x56, 0x69, 0xec, 0x2b, 0xac, 0xe6, 0xdf, 0xde, 0x18, 0x6d, 0x84,
	0xee, 0xfd, 0x06, 0x7c, 0xfb, 0x3b, 0x7a, 0x12, 0x9f, 0x3e, 0xeb, 0xa7, 0xa7, 0x1f, 0x0c, 0x66,
	0xba, 0x73, 0xe1, 0x5b, 0xdd, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x70, 0x13, 0x7e, 0xbe,
	0x02, 0x00, 0x00,
}
