// Code generated by protoc-gen-go.
// source: ss_logic.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2SLogicMsgId int32

const (
	S2SLogicMsgId_s2s_logic_false_msg_id       S2SLogicMsgId = 0
	S2SLogicMsgId_s2s_logic_min_msg_id         S2SLogicMsgId = 300
	S2SLogicMsgId_gl_gateway_info_ntf_id       S2SLogicMsgId = 301
	S2SLogicMsgId_gl_verify_token_req_id       S2SLogicMsgId = 302
	S2SLogicMsgId_lg_verify_token_ack_id       S2SLogicMsgId = 303
	S2SLogicMsgId_hc_select_player_list_req_id S2SLogicMsgId = 304
	S2SLogicMsgId_ch_select_player_list_ack_id S2SLogicMsgId = 305
	S2SLogicMsgId_hc_create_player_req_id      S2SLogicMsgId = 306
	S2SLogicMsgId_ch_create_player_ack_id      S2SLogicMsgId = 307
	S2SLogicMsgId_gh_select_hall_req_id        S2SLogicMsgId = 308
	S2SLogicMsgId_hg_select_hall_ack_id        S2SLogicMsgId = 309
	S2SLogicMsgId_s2s_gh_exit_game_req_id      S2SLogicMsgId = 310
	S2SLogicMsgId_s2s_gh_reconnect_game_req_id S2SLogicMsgId = 311
	S2SLogicMsgId_s2s_gh_kick_player_req_id    S2SLogicMsgId = 312
	S2SLogicMsgId_s2s_lgh_kick_player_req_id   S2SLogicMsgId = 313
	S2SLogicMsgId_s2s_hgl_kick_player_ack_id   S2SLogicMsgId = 314
	S2SLogicMsgId_hd_create_player_req_id      S2SLogicMsgId = 315
	S2SLogicMsgId_dh_create_player_ack_id      S2SLogicMsgId = 316
	S2SLogicMsgId_s2s_hgc_tranfer_msg_id       S2SLogicMsgId = 400
	S2SLogicMsgId_s2s_hc_tranfer_msg_id        S2SLogicMsgId = 401
	S2SLogicMsgId_s2s_gh_tranfer_msg_id        S2SLogicMsgId = 402
	S2SLogicMsgId_s2s_logic_max_msg_id         S2SLogicMsgId = 65535
)

var S2SLogicMsgId_name = map[int32]string{
	0:     "s2s_logic_false_msg_id",
	300:   "s2s_logic_min_msg_id",
	301:   "gl_gateway_info_ntf_id",
	302:   "gl_verify_token_req_id",
	303:   "lg_verify_token_ack_id",
	304:   "hc_select_player_list_req_id",
	305:   "ch_select_player_list_ack_id",
	306:   "hc_create_player_req_id",
	307:   "ch_create_player_ack_id",
	308:   "gh_select_hall_req_id",
	309:   "hg_select_hall_ack_id",
	310:   "s2s_gh_exit_game_req_id",
	311:   "s2s_gh_reconnect_game_req_id",
	312:   "s2s_gh_kick_player_req_id",
	313:   "s2s_lgh_kick_player_req_id",
	314:   "s2s_hgl_kick_player_ack_id",
	315:   "hd_create_player_req_id",
	316:   "dh_create_player_ack_id",
	400:   "s2s_hgc_tranfer_msg_id",
	401:   "s2s_hc_tranfer_msg_id",
	402:   "s2s_gh_tranfer_msg_id",
	65535: "s2s_logic_max_msg_id",
}
var S2SLogicMsgId_value = map[string]int32{
	"s2s_logic_false_msg_id":       0,
	"s2s_logic_min_msg_id":         300,
	"gl_gateway_info_ntf_id":       301,
	"gl_verify_token_req_id":       302,
	"lg_verify_token_ack_id":       303,
	"hc_select_player_list_req_id": 304,
	"ch_select_player_list_ack_id": 305,
	"hc_create_player_req_id":      306,
	"ch_create_player_ack_id":      307,
	"gh_select_hall_req_id":        308,
	"hg_select_hall_ack_id":        309,
	"s2s_gh_exit_game_req_id":      310,
	"s2s_gh_reconnect_game_req_id": 311,
	"s2s_gh_kick_player_req_id":    312,
	"s2s_lgh_kick_player_req_id":   313,
	"s2s_hgl_kick_player_ack_id":   314,
	"hd_create_player_req_id":      315,
	"dh_create_player_ack_id":      316,
	"s2s_hgc_tranfer_msg_id":       400,
	"s2s_hc_tranfer_msg_id":        401,
	"s2s_gh_tranfer_msg_id":        402,
	"s2s_logic_max_msg_id":         65535,
}

func (x S2SLogicMsgId) String() string {
	return proto.EnumName(S2SLogicMsgId_name, int32(x))
}
func (S2SLogicMsgId) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type GlGatewayInfoNtf struct {
	Ip               string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port             uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	PlayerTotalCount uint64 `protobuf:"varint,3,opt,name=playerTotalCount" json:"playerTotalCount,omitempty"`
}

func (m *GlGatewayInfoNtf) Reset()                    { *m = GlGatewayInfoNtf{} }
func (m *GlGatewayInfoNtf) String() string            { return proto.CompactTextString(m) }
func (*GlGatewayInfoNtf) ProtoMessage()               {}
func (*GlGatewayInfoNtf) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type GlVerifyTokenReq struct {
	Accountid uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Token     []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Playeruid uint64 `protobuf:"varint,3,opt,name=playeruid" json:"playeruid,omitempty"`
}

func (m *GlVerifyTokenReq) Reset()                    { *m = GlVerifyTokenReq{} }
func (m *GlVerifyTokenReq) String() string            { return proto.CompactTextString(m) }
func (*GlVerifyTokenReq) ProtoMessage()               {}
func (*GlVerifyTokenReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type LgVerifyTokenAck struct {
	Accountid uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Token     []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Errorcode uint32 `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
	Playeruid uint64 `protobuf:"varint,4,opt,name=playeruid" json:"playeruid,omitempty"`
}

func (m *LgVerifyTokenAck) Reset()                    { *m = LgVerifyTokenAck{} }
func (m *LgVerifyTokenAck) String() string            { return proto.CompactTextString(m) }
func (*LgVerifyTokenAck) ProtoMessage()               {}
func (*LgVerifyTokenAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

type SsPlayerBaseInfo struct {
	Playerid   uint64 `protobuf:"varint,1,opt,name=playerid" json:"playerid,omitempty"`
	Playername string `protobuf:"bytes,2,opt,name=playername" json:"playername,omitempty"`
}

func (m *SsPlayerBaseInfo) Reset()                    { *m = SsPlayerBaseInfo{} }
func (m *SsPlayerBaseInfo) String() string            { return proto.CompactTextString(m) }
func (*SsPlayerBaseInfo) ProtoMessage()               {}
func (*SsPlayerBaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

type HcSelectPlayerListReq struct {
	Accountid uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Playeruid uint64 `protobuf:"varint,2,opt,name=playeruid" json:"playeruid,omitempty"`
}

func (m *HcSelectPlayerListReq) Reset()                    { *m = HcSelectPlayerListReq{} }
func (m *HcSelectPlayerListReq) String() string            { return proto.CompactTextString(m) }
func (*HcSelectPlayerListReq) ProtoMessage()               {}
func (*HcSelectPlayerListReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

type ChSelectPlayerListAck struct {
	Accountid    uint64              `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Playeruid    uint64              `protobuf:"varint,2,opt,name=playeruid" json:"playeruid,omitempty"`
	Baseinfolist []*SsPlayerBaseInfo `protobuf:"bytes,3,rep,name=baseinfolist" json:"baseinfolist,omitempty"`
	Errorcode    uint32              `protobuf:"varint,4,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *ChSelectPlayerListAck) Reset()                    { *m = ChSelectPlayerListAck{} }
func (m *ChSelectPlayerListAck) String() string            { return proto.CompactTextString(m) }
func (*ChSelectPlayerListAck) ProtoMessage()               {}
func (*ChSelectPlayerListAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *ChSelectPlayerListAck) GetBaseinfolist() []*SsPlayerBaseInfo {
	if m != nil {
		return m.Baseinfolist
	}
	return nil
}

type HcCreatePlayerReq struct {
	Accountid  uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Playername string `protobuf:"bytes,2,opt,name=playername" json:"playername,omitempty"`
	Playerid   uint64 `protobuf:"varint,3,opt,name=playerid" json:"playerid,omitempty"`
}

func (m *HcCreatePlayerReq) Reset()                    { *m = HcCreatePlayerReq{} }
func (m *HcCreatePlayerReq) String() string            { return proto.CompactTextString(m) }
func (*HcCreatePlayerReq) ProtoMessage()               {}
func (*HcCreatePlayerReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

type ChCreatePlayerAck struct {
	Accountid  uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Playername string `protobuf:"bytes,2,opt,name=playername" json:"playername,omitempty"`
	Playerid   uint64 `protobuf:"varint,3,opt,name=playerid" json:"playerid,omitempty"`
	Errorcode  uint32 `protobuf:"varint,4,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *ChCreatePlayerAck) Reset()                    { *m = ChCreatePlayerAck{} }
func (m *ChCreatePlayerAck) String() string            { return proto.CompactTextString(m) }
func (*ChCreatePlayerAck) ProtoMessage()               {}
func (*ChCreatePlayerAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

type HdCreatePlayerReq struct {
	Accountid  uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Playerid   uint64 `protobuf:"varint,2,opt,name=playerid" json:"playerid,omitempty"`
	Playername string `protobuf:"bytes,3,opt,name=playername" json:"playername,omitempty"`
}

func (m *HdCreatePlayerReq) Reset()                    { *m = HdCreatePlayerReq{} }
func (m *HdCreatePlayerReq) String() string            { return proto.CompactTextString(m) }
func (*HdCreatePlayerReq) ProtoMessage()               {}
func (*HdCreatePlayerReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

type DhCreatePlayerAck struct {
	Accountid  uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Playerid   uint64 `protobuf:"varint,2,opt,name=playerid" json:"playerid,omitempty"`
	Playername string `protobuf:"bytes,3,opt,name=playername" json:"playername,omitempty"`
}

func (m *DhCreatePlayerAck) Reset()                    { *m = DhCreatePlayerAck{} }
func (m *DhCreatePlayerAck) String() string            { return proto.CompactTextString(m) }
func (*DhCreatePlayerAck) ProtoMessage()               {}
func (*DhCreatePlayerAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

type GhSelectHallReq struct {
	Accountid    uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	ClientsessId uint64 `protobuf:"varint,2,opt,name=clientsessId" json:"clientsessId,omitempty"`
	Playeruid    uint64 `protobuf:"varint,3,opt,name=playeruid" json:"playeruid,omitempty"`
}

func (m *GhSelectHallReq) Reset()                    { *m = GhSelectHallReq{} }
func (m *GhSelectHallReq) String() string            { return proto.CompactTextString(m) }
func (*GhSelectHallReq) ProtoMessage()               {}
func (*GhSelectHallReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

type HgSelectHallAck struct {
	Accountid uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Playeruid uint64 `protobuf:"varint,2,opt,name=playeruid" json:"playeruid,omitempty"`
}

func (m *HgSelectHallAck) Reset()                    { *m = HgSelectHallAck{} }
func (m *HgSelectHallAck) String() string            { return proto.CompactTextString(m) }
func (*HgSelectHallAck) ProtoMessage()               {}
func (*HgSelectHallAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

type S2S2CHgcTranferMsg struct {
	Msgid uint32 `protobuf:"varint,1,opt,name=msgid" json:"msgid,omitempty"`
	Datas []byte `protobuf:"bytes,2,opt,name=datas,proto3" json:"datas,omitempty"`
}

func (m *S2S2CHgcTranferMsg) Reset()                    { *m = S2S2CHgcTranferMsg{} }
func (m *S2S2CHgcTranferMsg) String() string            { return proto.CompactTextString(m) }
func (*S2S2CHgcTranferMsg) ProtoMessage()               {}
func (*S2S2CHgcTranferMsg) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

type S2SHcTranferMsg struct {
	Msgid uint32 `protobuf:"varint,1,opt,name=msgid" json:"msgid,omitempty"`
	Datas []byte `protobuf:"bytes,2,opt,name=datas,proto3" json:"datas,omitempty"`
}

func (m *S2SHcTranferMsg) Reset()                    { *m = S2SHcTranferMsg{} }
func (m *S2SHcTranferMsg) String() string            { return proto.CompactTextString(m) }
func (*S2SHcTranferMsg) ProtoMessage()               {}
func (*S2SHcTranferMsg) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{13} }

type S2SGhTranferMsg struct {
	Msgid     uint32 `protobuf:"varint,1,opt,name=msgid" json:"msgid,omitempty"`
	Datas     []byte `protobuf:"bytes,2,opt,name=datas,proto3" json:"datas,omitempty"`
	Accountid uint64 `protobuf:"varint,3,opt,name=accountid" json:"accountid,omitempty"`
}

func (m *S2SGhTranferMsg) Reset()                    { *m = S2SGhTranferMsg{} }
func (m *S2SGhTranferMsg) String() string            { return proto.CompactTextString(m) }
func (*S2SGhTranferMsg) ProtoMessage()               {}
func (*S2SGhTranferMsg) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{14} }

type S2SGhExitGameReq struct {
}

func (m *S2SGhExitGameReq) Reset()                    { *m = S2SGhExitGameReq{} }
func (m *S2SGhExitGameReq) String() string            { return proto.CompactTextString(m) }
func (*S2SGhExitGameReq) ProtoMessage()               {}
func (*S2SGhExitGameReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{15} }

type S2SGhKickPlayerReq struct {
}

func (m *S2SGhKickPlayerReq) Reset()                    { *m = S2SGhKickPlayerReq{} }
func (m *S2SGhKickPlayerReq) String() string            { return proto.CompactTextString(m) }
func (*S2SGhKickPlayerReq) ProtoMessage()               {}
func (*S2SGhKickPlayerReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{16} }

type S2SLghKickPlayerReq struct {
	Accountid       uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Token           []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Playeruid       uint64 `protobuf:"varint,3,opt,name=playeruid" json:"playeruid,omitempty"`
	Newgatewaysrvid uint64 `protobuf:"varint,4,opt,name=newgatewaysrvid" json:"newgatewaysrvid,omitempty"`
	Loginsrvid      uint64 `protobuf:"varint,5,opt,name=loginsrvid" json:"loginsrvid,omitempty"`
}

func (m *S2SLghKickPlayerReq) Reset()                    { *m = S2SLghKickPlayerReq{} }
func (m *S2SLghKickPlayerReq) String() string            { return proto.CompactTextString(m) }
func (*S2SLghKickPlayerReq) ProtoMessage()               {}
func (*S2SLghKickPlayerReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{17} }

type S2SHglKickPlayerAck struct {
	Accountid       uint64 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Token           []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Playeruid       uint64 `protobuf:"varint,3,opt,name=playeruid" json:"playeruid,omitempty"`
	Newgatewaysrvid uint64 `protobuf:"varint,4,opt,name=newgatewaysrvid" json:"newgatewaysrvid,omitempty"`
	Loginsrvid      uint64 `protobuf:"varint,5,opt,name=loginsrvid" json:"loginsrvid,omitempty"`
}

func (m *S2SHglKickPlayerAck) Reset()                    { *m = S2SHglKickPlayerAck{} }
func (m *S2SHglKickPlayerAck) String() string            { return proto.CompactTextString(m) }
func (*S2SHglKickPlayerAck) ProtoMessage()               {}
func (*S2SHglKickPlayerAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{18} }

type S2SGhReconnectGameReq struct {
	ClientsessId uint64 `protobuf:"varint,1,opt,name=clientsessId" json:"clientsessId,omitempty"`
}

func (m *S2SGhReconnectGameReq) Reset()                    { *m = S2SGhReconnectGameReq{} }
func (m *S2SGhReconnectGameReq) String() string            { return proto.CompactTextString(m) }
func (*S2SGhReconnectGameReq) ProtoMessage()               {}
func (*S2SGhReconnectGameReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{19} }

func init() {
	proto.RegisterType((*GlGatewayInfoNtf)(nil), "pb.gl_gateway_info_ntf")
	proto.RegisterType((*GlVerifyTokenReq)(nil), "pb.gl_verify_token_req")
	proto.RegisterType((*LgVerifyTokenAck)(nil), "pb.lg_verify_token_ack")
	proto.RegisterType((*SsPlayerBaseInfo)(nil), "pb.ss_player_base_info")
	proto.RegisterType((*HcSelectPlayerListReq)(nil), "pb.hc_select_player_list_req")
	proto.RegisterType((*ChSelectPlayerListAck)(nil), "pb.ch_select_player_list_ack")
	proto.RegisterType((*HcCreatePlayerReq)(nil), "pb.hc_create_player_req")
	proto.RegisterType((*ChCreatePlayerAck)(nil), "pb.ch_create_player_ack")
	proto.RegisterType((*HdCreatePlayerReq)(nil), "pb.hd_create_player_req")
	proto.RegisterType((*DhCreatePlayerAck)(nil), "pb.dh_create_player_ack")
	proto.RegisterType((*GhSelectHallReq)(nil), "pb.gh_select_hall_req")
	proto.RegisterType((*HgSelectHallAck)(nil), "pb.hg_select_hall_ack")
	proto.RegisterType((*S2S2CHgcTranferMsg)(nil), "pb.s2s2c_hgc_tranfer_msg")
	proto.RegisterType((*S2SHcTranferMsg)(nil), "pb.s2s_hc_tranfer_msg")
	proto.RegisterType((*S2SGhTranferMsg)(nil), "pb.s2s_gh_tranfer_msg")
	proto.RegisterType((*S2SGhExitGameReq)(nil), "pb.s2s_gh_exit_game_req")
	proto.RegisterType((*S2SGhKickPlayerReq)(nil), "pb.s2s_gh_kick_player_req")
	proto.RegisterType((*S2SLghKickPlayerReq)(nil), "pb.s2s_lgh_kick_player_req")
	proto.RegisterType((*S2SHglKickPlayerAck)(nil), "pb.s2s_hgl_kick_player_ack")
	proto.RegisterType((*S2SGhReconnectGameReq)(nil), "pb.s2s_gh_reconnect_game_req")
	proto.RegisterEnum("pb.S2SLogicMsgId", S2SLogicMsgId_name, S2SLogicMsgId_value)
}

var fileDescriptor5 = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x56, 0x4b, 0x6f, 0xd3, 0x4a,
	0x14, 0xbe, 0x71, 0xd2, 0xab, 0xdb, 0x73, 0x9b, 0x52, 0x4d, 0xd3, 0x36, 0x29, 0x15, 0x0f, 0xaf,
	0xaa, 0x2e, 0xba, 0x08, 0x4b, 0x16, 0x20, 0x75, 0x55, 0x09, 0x24, 0x70, 0x91, 0xd8, 0x61, 0x4d,
	0xc6, 0x13, 0xc7, 0x8a, 0x63, 0x07, 0xcf, 0xf4, 0xf5, 0x03, 0xd8, 0x22, 0xe0, 0x4f, 0xb0, 0xe1,
	0x59, 0x28, 0xef, 0xff, 0x56, 0xe6, 0x8c, 0x63, 0x37, 0x8e, 0x9d, 0xa6, 0x6d, 0x10, 0xab, 0x78,
	0xce, 0x77, 0x72, 0xce, 0x99, 0xef, 0xbc, 0x06, 0xe6, 0x85, 0xb0, 0xfd, 0xd0, 0xf5, 0xd8, 0x66,
	0x3f, 0x0a, 0x65, 0x48, 0x8c, 0x7e, 0xcb, 0xe4, 0xb0, 0xe8, 0xfa, 0xb6, 0x4b, 0x25, 0xdf, 0xa7,
	0x87, 0xb6, 0x17, 0xb4, 0x43, 0x3b, 0x90, 0x6d, 0x32, 0x0f, 0x86, 0xd7, 0xaf, 0x97, 0x6e, 0x94,
	0xd6, 0x67, 0x2d, 0xf5, 0x45, 0x08, 0x54, 0xfa, 0x61, 0x24, 0xeb, 0x86, 0x92, 0x54, 0x2d, 0xfd,
	0x4d, 0x36, 0x60, 0xa1, 0xef, 0xd3, 0x43, 0x1e, 0x3d, 0x0a, 0x25, 0xf5, 0xb7, 0xc2, 0xdd, 0x40,
	0xd6, 0xcb, 0x0a, 0xaf, 0x58, 0x39, 0xb9, 0xe9, 0x6a, 0x37, 0x7b, 0x3c, 0xf2, 0xda, 0x87, 0xb6,
	0x0c, 0xbb, 0x3c, 0xb0, 0x23, 0xfe, 0x94, 0xac, 0xc1, 0x2c, 0x65, 0x0c, 0x35, 0x3c, 0x47, 0x7b,
	0xab, 0x58, 0xa7, 0x02, 0x52, 0x83, 0x19, 0xad, 0xaa, 0xbd, 0xce, 0x59, 0xf1, 0x01, 0xff, 0x13,
	0x9b, 0xdf, 0x55, 0xff, 0x89, 0xfd, 0x9d, 0x0a, 0xcc, 0x67, 0x25, 0x58, 0xf4, 0xdd, 0xac, 0x27,
	0xca, 0xba, 0x97, 0xf5, 0xc4, 0xa3, 0x28, 0x8c, 0x58, 0xe8, 0x70, 0xed, 0xa9, 0x6a, 0x9d, 0x0a,
	0xb2, 0x71, 0x54, 0x46, 0xe3, 0x78, 0x08, 0x8b, 0x8a, 0xed, 0xf8, 0x6c, 0xb7, 0xa8, 0xe0, 0x9a,
	0x5b, 0xb2, 0x0a, 0xff, 0xc5, 0xb2, 0x34, 0x8a, 0xf4, 0x4c, 0xae, 0x01, 0xc4, 0xdf, 0x01, 0xed,
	0x71, 0x1d, 0xc9, 0xac, 0x35, 0x24, 0x31, 0x1f, 0x43, 0xa3, 0xc3, 0x6c, 0xc1, 0x7d, 0xce, 0x64,
	0x62, 0xd9, 0xf7, 0x84, 0x3c, 0x07, 0x93, 0x99, 0x58, 0x8d, 0xd1, 0x58, 0x8f, 0x4a, 0xd0, 0x60,
	0x9d, 0x22, 0xcb, 0x93, 0x99, 0x3b, 0xd3, 0x32, 0xb9, 0x0d, 0x73, 0x78, 0x77, 0xbc, 0x3a, 0xda,
	0x53, 0x24, 0x96, 0xd7, 0xff, 0x6f, 0xae, 0x6c, 0xf6, 0x5b, 0x9b, 0x05, 0xec, 0x58, 0x19, 0xe5,
	0x2c, 0xfd, 0x95, 0x11, 0xfa, 0xcd, 0x3e, 0xd4, 0x14, 0x1b, 0x2c, 0xe2, 0xaa, 0x74, 0x13, 0x4b,
	0x93, 0x89, 0x98, 0xc0, 0x71, 0x26, 0x3f, 0xe5, 0x6c, 0x7e, 0xcc, 0xe7, 0x25, 0xa8, 0x29, 0x9a,
	0xb2, 0x2e, 0x27, 0x33, 0x34, 0x85, 0xcb, 0x73, 0x50, 0xe0, 0x5c, 0x98, 0x82, 0x61, 0x7f, 0xc6,
	0x99, 0x25, 0x58, 0xce, 0x95, 0xa0, 0xf2, 0xe8, 0x5c, 0x9c, 0x81, 0x69, 0x3c, 0x4a, 0x20, 0x6e,
	0x5a, 0x9a, 0x1d, 0xea, 0xfb, 0xe7, 0xb8, 0xa1, 0x09, 0x73, 0xcc, 0xf7, 0x78, 0x20, 0x05, 0x17,
	0x62, 0x3b, 0xf1, 0x99, 0x91, 0x4d, 0x98, 0x22, 0x0f, 0x80, 0x74, 0xdc, 0x8c, 0xd7, 0x29, 0x3b,
	0xc1, 0xdc, 0x82, 0x25, 0xd1, 0x14, 0x4d, 0x66, 0x77, 0x5c, 0x66, 0xcb, 0x88, 0x06, 0x6d, 0x45,
	0x5d, 0x4f, 0xb8, 0x38, 0x7a, 0xd4, 0xcf, 0xc0, 0x60, 0xd5, 0x8a, 0x0f, 0x28, 0x75, 0xa8, 0xa4,
	0x22, 0x19, 0x48, 0xfa, 0x60, 0xde, 0x05, 0xa2, 0x8c, 0xd8, 0x9d, 0xcb, 0x5b, 0x78, 0x12, 0x5b,
	0x50, 0x94, 0x5e, 0xd2, 0x42, 0x96, 0x84, 0xf2, 0x08, 0x09, 0xe6, 0x32, 0xd4, 0x06, 0xf6, 0xf9,
	0x81, 0x27, 0xd5, 0x5e, 0xe9, 0x71, 0x4c, 0x98, 0x59, 0x87, 0xe5, 0x81, 0xbc, 0xeb, 0xb1, 0xee,
	0x50, 0xb1, 0x9a, 0xc7, 0x25, 0x58, 0x41, 0xc8, 0xcf, 0x63, 0x7f, 0x7e, 0x3d, 0x90, 0x75, 0xb8,
	0x12, 0xf0, 0xfd, 0xc1, 0xba, 0x13, 0xd1, 0x5e, 0x3a, 0xba, 0x47, 0xc5, 0x58, 0x98, 0xb8, 0x2b,
	0x83, 0x58, 0x69, 0x46, 0x2b, 0x0d, 0x49, 0xd2, 0xb8, 0x3b, 0x6a, 0xaf, 0x0d, 0xc7, 0x3d, 0xc5,
	0xb2, 0xf9, 0x2b, 0x71, 0xdf, 0x81, 0xc6, 0x20, 0x13, 0x11, 0x67, 0x61, 0x10, 0x60, 0x85, 0x27,
	0x69, 0xca, 0x75, 0x4e, 0x29, 0xdf, 0x39, 0x1b, 0xaf, 0x67, 0xa0, 0xba, 0xd3, 0xdc, 0xb9, 0x87,
	0x0f, 0x89, 0xfb, 0xc2, 0xdd, 0xc6, 0xfe, 0xd6, 0xc9, 0xd5, 0x4f, 0x0b, 0xbb, 0x4d, 0x7d, 0x35,
	0xce, 0x55, 0x05, 0xd9, 0x9e, 0xb3, 0xf0, 0x0f, 0x69, 0xc4, 0x05, 0x11, 0x63, 0x3d, 0x2f, 0x48,
	0x90, 0x37, 0x06, 0xb9, 0x0a, 0xcb, 0x05, 0x4f, 0x0f, 0x04, 0xdf, 0x26, 0xe0, 0xe8, 0x83, 0x01,
	0xc1, 0x77, 0x1a, 0x2c, 0xd8, 0xf1, 0x08, 0xbe, 0x37, 0xc8, 0x4d, 0x58, 0x1b, 0xbb, 0x26, 0x51,
	0xe5, 0x83, 0x56, 0x19, 0xbb, 0xef, 0x50, 0xe5, 0xa3, 0xa1, 0xd2, 0xb1, 0x52, 0xb4, 0x5e, 0x10,
	0x3d, 0xd2, 0x68, 0xd1, 0x26, 0x40, 0xf4, 0x93, 0xa1, 0xf8, 0x58, 0xca, 0xcf, 0x2c, 0xc4, 0x3e,
	0x6b, 0x2c, 0x3f, 0x59, 0x10, 0x3b, 0xd6, 0x56, 0x8b, 0x9a, 0x07, 0xd1, 0x2f, 0x3a, 0xe8, 0xb1,
	0x89, 0x43, 0x95, 0xaf, 0x86, 0xca, 0x7d, 0xa3, 0xb8, 0xcb, 0x10, 0xff, 0x66, 0x90, 0xeb, 0xb0,
	0x3a, 0xa6, 0xd5, 0x50, 0xe1, 0x7b, 0xaa, 0x50, 0x50, 0xd3, 0xa8, 0xf0, 0x23, 0xa6, 0xc5, 0x29,
	0xa6, 0xe5, 0xa7, 0x46, 0x9d, 0x31, 0xb4, 0xfc, 0xd2, 0x59, 0x8b, 0x8d, 0x67, 0xc6, 0x17, 0x82,
	0x2f, 0xca, 0xc8, 0x4b, 0x7e, 0xb4, 0x21, 0xf6, 0x32, 0xc5, 0xb2, 0x43, 0x0b, 0xb1, 0x57, 0x88,
	0x0d, 0xd7, 0x17, 0x3d, 0x48, 0xa0, 0x93, 0x93, 0x72, 0xeb, 0x5f, 0xfd, 0xcc, 0xbd, 0xf5, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x17, 0x99, 0x06, 0x7d, 0xf8, 0x0a, 0x00, 0x00,
}
