// Code generated by protoc-gen-go.
// source: ts_client.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2TSLogicMsgId int32

const (
	C2TSLogicMsgId_c2ts_logic_min_msg_id     C2TSLogicMsgId = 0
	C2TSLogicMsgId_c2ts_cg_tranfer_msg_id    C2TSLogicMsgId = 3
	C2TSLogicMsgId_ts2c_gc_tranfer_msg_id    C2TSLogicMsgId = 4
	C2TSLogicMsgId_c2ts_select_tsgate_req_id C2TSLogicMsgId = 5
	C2TSLogicMsgId_ts2c_select_tsgate_ack_id C2TSLogicMsgId = 6
	C2TSLogicMsgId_c2ts_tsgate_verify_req_id C2TSLogicMsgId = 7
	C2TSLogicMsgId_ts2c_tsgate_verify_ack_id C2TSLogicMsgId = 8
	C2TSLogicMsgId_c2ts_update_rank_req_id   C2TSLogicMsgId = 20
	C2TSLogicMsgId_ts2c_update_rank_ack_id   C2TSLogicMsgId = 21
	C2TSLogicMsgId_c2ts_query_rank_req_id    C2TSLogicMsgId = 22
	C2TSLogicMsgId_ts2c_query_rank_ack_id    C2TSLogicMsgId = 23
	C2TSLogicMsgId_c2ts_clear_all_req_id     C2TSLogicMsgId = 24
	C2TSLogicMsgId_ts2c_clear_all_ack_id     C2TSLogicMsgId = 25
	C2TSLogicMsgId_c2ts_clear_player_req_id  C2TSLogicMsgId = 26
	C2TSLogicMsgId_ts2c_clear_player_ack_id  C2TSLogicMsgId = 27
	C2TSLogicMsgId_c2ts_logic_max_msg_id     C2TSLogicMsgId = 65535
)

var C2TSLogicMsgId_name = map[int32]string{
	0:     "c2ts_logic_min_msg_id",
	3:     "c2ts_cg_tranfer_msg_id",
	4:     "ts2c_gc_tranfer_msg_id",
	5:     "c2ts_select_tsgate_req_id",
	6:     "ts2c_select_tsgate_ack_id",
	7:     "c2ts_tsgate_verify_req_id",
	8:     "ts2c_tsgate_verify_ack_id",
	20:    "c2ts_update_rank_req_id",
	21:    "ts2c_update_rank_ack_id",
	22:    "c2ts_query_rank_req_id",
	23:    "ts2c_query_rank_ack_id",
	24:    "c2ts_clear_all_req_id",
	25:    "ts2c_clear_all_ack_id",
	26:    "c2ts_clear_player_req_id",
	27:    "ts2c_clear_player_ack_id",
	65535: "c2ts_logic_max_msg_id",
}
var C2TSLogicMsgId_value = map[string]int32{
	"c2ts_logic_min_msg_id":     0,
	"c2ts_cg_tranfer_msg_id":    3,
	"ts2c_gc_tranfer_msg_id":    4,
	"c2ts_select_tsgate_req_id": 5,
	"ts2c_select_tsgate_ack_id": 6,
	"c2ts_tsgate_verify_req_id": 7,
	"ts2c_tsgate_verify_ack_id": 8,
	"c2ts_update_rank_req_id":   20,
	"ts2c_update_rank_ack_id":   21,
	"c2ts_query_rank_req_id":    22,
	"ts2c_query_rank_ack_id":    23,
	"c2ts_clear_all_req_id":     24,
	"ts2c_clear_all_ack_id":     25,
	"c2ts_clear_player_req_id":  26,
	"ts2c_clear_player_ack_id":  27,
	"c2ts_logic_max_msg_id":     65535,
}

func (x C2TSLogicMsgId) String() string {
	return proto.EnumName(C2TSLogicMsgId_name, int32(x))
}
func (C2TSLogicMsgId) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

type C2TsSelectTsgateReq struct {
	BalanceToken string `protobuf:"bytes,1,opt,name=balance_token,json=balanceToken" json:"balance_token,omitempty"`
}

func (m *C2TsSelectTsgateReq) Reset()                    { *m = C2TsSelectTsgateReq{} }
func (m *C2TsSelectTsgateReq) String() string            { return proto.CompactTextString(m) }
func (*C2TsSelectTsgateReq) ProtoMessage()               {}
func (*C2TsSelectTsgateReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

type Ts2CSelectTsgateAck struct {
	RemoteAddr   string `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr" json:"remote_addr,omitempty"`
	GatewayToken string `protobuf:"bytes,2,opt,name=gateway_token,json=gatewayToken" json:"gateway_token,omitempty"`
}

func (m *Ts2CSelectTsgateAck) Reset()                    { *m = Ts2CSelectTsgateAck{} }
func (m *Ts2CSelectTsgateAck) String() string            { return proto.CompactTextString(m) }
func (*Ts2CSelectTsgateAck) ProtoMessage()               {}
func (*Ts2CSelectTsgateAck) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

type C2TsTsgateVerifyReq struct {
	GatewayToken string `protobuf:"bytes,1,opt,name=gateway_token,json=gatewayToken" json:"gateway_token,omitempty"`
}

func (m *C2TsTsgateVerifyReq) Reset()                    { *m = C2TsTsgateVerifyReq{} }
func (m *C2TsTsgateVerifyReq) String() string            { return proto.CompactTextString(m) }
func (*C2TsTsgateVerifyReq) ProtoMessage()               {}
func (*C2TsTsgateVerifyReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

type Ts2CTsgateVerifyAck struct {
}

func (m *Ts2CTsgateVerifyAck) Reset()                    { *m = Ts2CTsgateVerifyAck{} }
func (m *Ts2CTsgateVerifyAck) String() string            { return proto.CompactTextString(m) }
func (*Ts2CTsgateVerifyAck) ProtoMessage()               {}
func (*Ts2CTsgateVerifyAck) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

type C2TsCgTranferMsg struct {
	Tid   uint32 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Msgid uint32 `protobuf:"varint,2,opt,name=msgid" json:"msgid,omitempty"`
	Datas []byte `protobuf:"bytes,3,opt,name=datas,proto3" json:"datas,omitempty"`
	Cbid  uint64 `protobuf:"varint,4,opt,name=cbid" json:"cbid,omitempty"`
}

func (m *C2TsCgTranferMsg) Reset()                    { *m = C2TsCgTranferMsg{} }
func (m *C2TsCgTranferMsg) String() string            { return proto.CompactTextString(m) }
func (*C2TsCgTranferMsg) ProtoMessage()               {}
func (*C2TsCgTranferMsg) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

type Ts2CGcTranferMsg struct {
	Tid   uint32 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Msgid uint32 `protobuf:"varint,2,opt,name=msgid" json:"msgid,omitempty"`
	Datas []byte `protobuf:"bytes,3,opt,name=datas,proto3" json:"datas,omitempty"`
	Cbid  uint64 `protobuf:"varint,4,opt,name=cbid" json:"cbid,omitempty"`
}

func (m *Ts2CGcTranferMsg) Reset()                    { *m = Ts2CGcTranferMsg{} }
func (m *Ts2CGcTranferMsg) String() string            { return proto.CompactTextString(m) }
func (*Ts2CGcTranferMsg) ProtoMessage()               {}
func (*Ts2CGcTranferMsg) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{5} }

type C2TsUpdateRankReq struct {
	RankInfo *RankItem `protobuf:"bytes,1,opt,name=rank_info,json=rankInfo" json:"rank_info,omitempty"`
}

func (m *C2TsUpdateRankReq) Reset()                    { *m = C2TsUpdateRankReq{} }
func (m *C2TsUpdateRankReq) String() string            { return proto.CompactTextString(m) }
func (*C2TsUpdateRankReq) ProtoMessage()               {}
func (*C2TsUpdateRankReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{6} }

func (m *C2TsUpdateRankReq) GetRankInfo() *RankItem {
	if m != nil {
		return m.RankInfo
	}
	return nil
}

type Ts2CUpdateRankAck struct {
	Tid       uint32 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Playerid  uint64 `protobuf:"varint,2,opt,name=playerid" json:"playerid,omitempty"`
	Errorcode uint32 `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Ts2CUpdateRankAck) Reset()                    { *m = Ts2CUpdateRankAck{} }
func (m *Ts2CUpdateRankAck) String() string            { return proto.CompactTextString(m) }
func (*Ts2CUpdateRankAck) ProtoMessage()               {}
func (*Ts2CUpdateRankAck) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{7} }

type C2TsQueryRankReq struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Topn     uint32 `protobuf:"varint,2,opt,name=topn" json:"topn,omitempty"`
}

func (m *C2TsQueryRankReq) Reset()                    { *m = C2TsQueryRankReq{} }
func (m *C2TsQueryRankReq) String() string            { return proto.CompactTextString(m) }
func (*C2TsQueryRankReq) ProtoMessage()               {}
func (*C2TsQueryRankReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{8} }

type Ts2CQueryRankAck struct {
	Tid        uint32      `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	PlayerId   uint64      `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	RankList   []*RankItem `protobuf:"bytes,3,rep,name=rank_list,json=rankList" json:"rank_list,omitempty"`
	PlayerRank *RankItem   `protobuf:"bytes,4,opt,name=player_rank,json=playerRank" json:"player_rank,omitempty"`
	Errorcode  uint32      `protobuf:"varint,5,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Ts2CQueryRankAck) Reset()                    { *m = Ts2CQueryRankAck{} }
func (m *Ts2CQueryRankAck) String() string            { return proto.CompactTextString(m) }
func (*Ts2CQueryRankAck) ProtoMessage()               {}
func (*Ts2CQueryRankAck) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{9} }

func (m *Ts2CQueryRankAck) GetRankList() []*RankItem {
	if m != nil {
		return m.RankList
	}
	return nil
}

func (m *Ts2CQueryRankAck) GetPlayerRank() *RankItem {
	if m != nil {
		return m.PlayerRank
	}
	return nil
}

type C2TsClearAllReq struct {
}

func (m *C2TsClearAllReq) Reset()                    { *m = C2TsClearAllReq{} }
func (m *C2TsClearAllReq) String() string            { return proto.CompactTextString(m) }
func (*C2TsClearAllReq) ProtoMessage()               {}
func (*C2TsClearAllReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{10} }

type Ts2CClearAllAck struct {
	Tid       uint32 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Errorcode uint32 `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Ts2CClearAllAck) Reset()                    { *m = Ts2CClearAllAck{} }
func (m *Ts2CClearAllAck) String() string            { return proto.CompactTextString(m) }
func (*Ts2CClearAllAck) ProtoMessage()               {}
func (*Ts2CClearAllAck) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{11} }

type C2TsClearPlayerReq struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *C2TsClearPlayerReq) Reset()                    { *m = C2TsClearPlayerReq{} }
func (m *C2TsClearPlayerReq) String() string            { return proto.CompactTextString(m) }
func (*C2TsClearPlayerReq) ProtoMessage()               {}
func (*C2TsClearPlayerReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{12} }

type Ts2CClearPlayerAck struct {
	Tid       uint32 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	PlayerId  uint64 `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Errorcode uint32 `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Ts2CClearPlayerAck) Reset()                    { *m = Ts2CClearPlayerAck{} }
func (m *Ts2CClearPlayerAck) String() string            { return proto.CompactTextString(m) }
func (*Ts2CClearPlayerAck) ProtoMessage()               {}
func (*Ts2CClearPlayerAck) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{13} }

func init() {
	proto.RegisterType((*C2TsSelectTsgateReq)(nil), "pb.c2ts_select_tsgate_req")
	proto.RegisterType((*Ts2CSelectTsgateAck)(nil), "pb.ts2c_select_tsgate_ack")
	proto.RegisterType((*C2TsTsgateVerifyReq)(nil), "pb.c2ts_tsgate_verify_req")
	proto.RegisterType((*Ts2CTsgateVerifyAck)(nil), "pb.ts2c_tsgate_verify_ack")
	proto.RegisterType((*C2TsCgTranferMsg)(nil), "pb.c2ts_cg_tranfer_msg")
	proto.RegisterType((*Ts2CGcTranferMsg)(nil), "pb.ts2c_gc_tranfer_msg")
	proto.RegisterType((*C2TsUpdateRankReq)(nil), "pb.c2ts_update_rank_req")
	proto.RegisterType((*Ts2CUpdateRankAck)(nil), "pb.ts2c_update_rank_ack")
	proto.RegisterType((*C2TsQueryRankReq)(nil), "pb.c2ts_query_rank_req")
	proto.RegisterType((*Ts2CQueryRankAck)(nil), "pb.ts2c_query_rank_ack")
	proto.RegisterType((*C2TsClearAllReq)(nil), "pb.c2ts_clear_all_req")
	proto.RegisterType((*Ts2CClearAllAck)(nil), "pb.ts2c_clear_all_ack")
	proto.RegisterType((*C2TsClearPlayerReq)(nil), "pb.c2ts_clear_player_req")
	proto.RegisterType((*Ts2CClearPlayerAck)(nil), "pb.ts2c_clear_player_ack")
	proto.RegisterEnum("pb.C2TSLogicMsgId", C2TSLogicMsgId_name, C2TSLogicMsgId_value)
}

var fileDescriptor9 = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x8e, 0xd3, 0x3c,
	0x14, 0xfd, 0xda, 0xb4, 0xf3, 0xb5, 0xb7, 0x53, 0x18, 0x99, 0xb6, 0xd3, 0x76, 0x40, 0xa0, 0xb0,
	0x41, 0xb3, 0xe8, 0xa2, 0xb0, 0x65, 0xc1, 0x8f, 0x90, 0x46, 0x1a, 0x36, 0x61, 0xd6, 0x44, 0x4e,
	0xe2, 0x46, 0x51, 0xf3, 0x37, 0x8e, 0x07, 0xe8, 0xcb, 0xf1, 0x2c, 0xbc, 0xc9, 0xe0, 0x6b, 0xbb,
	0x69, 0xd3, 0x1a, 0x90, 0x90, 0xd8, 0x39, 0xe7, 0xf8, 0x1e, 0x1f, 0x1f, 0x5f, 0x3b, 0xf0, 0x50,
	0x54, 0x7e, 0x98, 0x26, 0x2c, 0x17, 0x8b, 0x92, 0x17, 0xa2, 0x20, 0xed, 0x32, 0x98, 0x2b, 0xb0,
	0xc8, 0xb2, 0x22, 0xd7, 0xa0, 0xfb, 0x1a, 0x26, 0xe1, 0x52, 0x82, 0x15, 0x4b, 0x59, 0x28, 0x7c,
	0x51, 0xc5, 0x54, 0x30, 0x9f, 0xb3, 0x5b, 0xf2, 0x1c, 0x86, 0x01, 0x4d, 0x69, 0x1e, 0x32, 0x5f,
	0x14, 0x6b, 0x96, 0x4f, 0x5b, 0xcf, 0x5a, 0x2f, 0xfa, 0xde, 0xa9, 0x01, 0x6f, 0x10, 0x73, 0x3f,
	0xc3, 0x44, 0x54, 0xcb, 0xf0, 0xa0, 0x9c, 0x86, 0x6b, 0xf2, 0x14, 0x06, 0x9c, 0x65, 0x05, 0x7e,
	0x45, 0x11, 0x37, 0xc5, 0xa0, 0xa1, 0x37, 0x12, 0x41, 0x7d, 0x9c, 0xfc, 0x95, 0x6e, 0x8c, 0x7e,
	0x5b, 0xeb, 0x1b, 0x50, 0xeb, 0x6f, 0xed, 0x19, 0xe1, 0x2f, 0x8c, 0x27, 0xab, 0xcd, 0xd6, 0x5e,
	0xb3, 0xbc, 0x65, 0x29, 0x9f, 0x1a, 0x7b, 0xcd, 0x72, 0x69, 0xcf, 0x8d, 0xe1, 0x91, 0x12, 0x0e,
	0x63, 0x5f, 0x70, 0x9a, 0xaf, 0x18, 0xf7, 0xb3, 0x2a, 0x26, 0x67, 0xe0, 0x88, 0x24, 0x52, 0x5a,
	0x43, 0x0f, 0x87, 0x64, 0x04, 0x5d, 0x49, 0x48, 0xac, 0xad, 0x30, 0xfd, 0x81, 0x68, 0x44, 0x05,
	0xad, 0xa6, 0x8e, 0x44, 0x4f, 0x3d, 0xfd, 0x41, 0x08, 0x74, 0xc2, 0x40, 0x4e, 0xed, 0x48, 0xb0,
	0xe3, 0xa9, 0x31, 0x2e, 0xa4, 0x2c, 0xc4, 0xe1, 0x3f, 0x5e, 0xe8, 0x2d, 0x8c, 0xd4, 0x8e, 0xee,
	0xca, 0x48, 0x1d, 0x21, 0xcd, 0xd7, 0x2a, 0xa8, 0x4b, 0xe8, 0xab, 0x71, 0x92, 0xaf, 0x0a, 0xb5,
	0xde, 0x60, 0x39, 0x5c, 0x94, 0xc1, 0x42, 0x83, 0x82, 0x65, 0x5e, 0x0f, 0x87, 0x57, 0x92, 0x76,
	0x03, 0x18, 0x29, 0xb3, 0xfb, 0x1a, 0x78, 0x98, 0xc7, 0x6e, 0xe7, 0xd0, 0x2b, 0x53, 0xba, 0x91,
	0x81, 0x6a, 0xc3, 0x1d, 0xaf, 0xfe, 0x26, 0x8f, 0xa1, 0xcf, 0x38, 0x2f, 0x78, 0x58, 0x44, 0x4c,
	0xf9, 0x1e, 0x7a, 0x3b, 0xc0, 0xfd, 0x60, 0x92, 0xbf, 0xbd, 0x63, 0x7c, 0xb3, 0xb3, 0x79, 0x01,
	0x7d, 0x2d, 0xe0, 0x9b, 0x85, 0x6a, 0xc5, 0xab, 0x08, 0xf7, 0x2b, 0x8a, 0x32, 0x37, 0xd1, 0xa8,
	0xb1, 0xfb, 0xbd, 0x65, 0x92, 0xdd, 0x13, 0xb2, 0x7b, 0x6d, 0x48, 0xb7, 0x0f, 0xa4, 0xb7, 0xf1,
	0xa4, 0x49, 0x25, 0xa4, 0x59, 0xe7, 0x17, 0xf1, 0x5c, 0x4b, 0x9a, 0x2c, 0x60, 0x60, 0x84, 0x10,
	0x52, 0xe9, 0x1f, 0xcd, 0x06, 0x3d, 0xc3, 0x93, 0x40, 0x33, 0x88, 0xee, 0x61, 0x10, 0x23, 0x20,
	0xba, 0x05, 0x53, 0x46, 0xb9, 0x4f, 0xd3, 0x14, 0x73, 0x70, 0xdf, 0x03, 0x51, 0xbb, 0xda, 0xa1,
	0xf6, 0x4d, 0x35, 0xb4, 0xdb, 0x87, 0xda, 0xaf, 0x60, 0xbc, 0xa7, 0xbd, 0x35, 0xfd, 0x87, 0x98,
	0xdd, 0x08, 0xc6, 0x7b, 0x6b, 0x9b, 0x79, 0x7f, 0x91, 0xe9, 0x6f, 0x1b, 0xe0, 0xf2, 0x87, 0x03,
	0x0f, 0xde, 0x2d, 0x6f, 0x3e, 0x5d, 0x17, 0x71, 0x12, 0x7e, 0xac, 0x62, 0x59, 0x30, 0x33, 0x76,
	0x53, 0x84, 0xfc, 0x2c, 0xc9, 0xf1, 0x8e, 0x48, 0xe5, 0xb3, 0xff, 0x64, 0xa3, 0x4d, 0x2c, 0x17,
	0x15, 0x39, 0x07, 0x39, 0xcb, 0xdd, 0x42, 0xae, 0x43, 0x9e, 0xc0, 0xcc, 0xfe, 0xb0, 0x21, 0xdd,
	0x45, 0xda, 0xfe, 0x70, 0x21, 0x7d, 0x52, 0x57, 0x1f, 0xbd, 0x3b, 0x48, 0xff, 0x5f, 0x57, 0x1f,
	0xbd, 0x2b, 0x48, 0xf7, 0x64, 0x38, 0xe7, 0xb6, 0xab, 0x88, 0xe4, 0x08, 0x49, 0xdb, 0x1d, 0x43,
	0x72, 0x5c, 0xef, 0xb6, 0x79, 0x39, 0x90, 0x9b, 0xd4, 0xbb, 0x6d, 0xf6, 0x3b, 0x72, 0xe7, 0x75,
	0x80, 0x8d, 0x5e, 0x42, 0x6a, 0x8a, 0xd4, 0x71, 0x43, 0x21, 0x35, 0x93, 0xe7, 0x34, 0xb5, 0x76,
	0x09, 0xb2, 0x73, 0x64, 0xad, 0xdd, 0x80, 0xec, 0x85, 0xdc, 0x46, 0xe3, 0xc8, 0xe8, 0xb7, 0x6d,
	0xf4, 0xf7, 0xf7, 0x4e, 0x70, 0xa2, 0x7e, 0x2e, 0x2f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x1d, 0x37, 0xda, 0x84, 0x06, 0x00, 0x00,
}
