server:
    serverid: 1
    servertype: 1
    token: "123456" 
    inter: ""   
    outer: ""
log:
    path: "./log"
    level: 1

redis:
    name: "redis_0"
    host: "127.0.0.1"
    port: 6379
    password:     

db:
  connmaxcount:  1
  tablemaxcount: 1
  dblist:
  -
    name:  logindb_0
    host:  "127.0.0.1"
    port:  3306
    user:  "root"
    password: "123456"
    charset: "utf8"


http:
  url: "127.0.0.1:1010"
  cert: 
  key: 

